backend:
  name: github
  repo: outreachedmanagement-prog/hostletprompt
  branch: main
  site_domain: polite-mooncake-b5886f.netlify.app

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"

    media_folder: "images"
    public_folder: "/images"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Featured Image"
        name: "image"
        widget: "image"
        required: true

      - label: "Body"
        name: "body"
        widget: "markdown"
