backend:
  name: github
  repo: outreachedmanagement-prog/hostletprompt
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Featured Image"
        name: "image"
        widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"
